version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/app:/app
      # - ./app:/app
    ports:
      - "80:80"
    environment:
      - NUM_PROCS=2
      - API_PROCS=144
      - CRON_PROCS=0
      - APP_ENV=levi-test
      - SUPERVISOR_APP_STOPWAITSECS=20
      - SECRET_KEY=big-secret
      - FLASK_DEBUG=1
      - ACCOUNT_SID=AC06a51df77203c3010726688868097d65 
      - API_KEY=SK24d7e1313a1e95444c27c2a610172541
      - API_SECRET=vyHjwndLbaFsxhwEIHzmLNGgp4R0K9A1
